name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eshanshz6/ubuntu-image-autobuild:latest
    - name: Push the docker image
      run: docker image -u eshanshz6 -p ${{ secrets.DOCKER_TOKEN }} && docker push eshanshz6/ubuntu-image-autobuild:latest
